#!/bin/bash
shopt -s histappend             # append new history items to .bash_history
export HISTCONTROL=ignorespace  # leading space hides commands from history
export HISTFILESIZE=10000       # increase history file size (default is 500)
export HISTSIZE=${HISTFILESIZE} # increase history size (default is 500)

. "$HOME/.atuin/bin/env"

[[ -f ~/.bash-preexec.sh ]] && source $HOME/.bash-preexec.sh
eval "$(atuin init bash)"
