#!/bin/bash
# vim: set et fenc=utf-8 ff=unix sts=4 sw=4 ts=8 :
common_lib="$(dirname "$(readlink -f "$0")")/common-lib"
if [[ -f "$common_lib" ]]; then
    # shellcheck source=common-lib
    . "$common_lib"
else
    echo "[FAIL] Cannot find common-lib."
    exit 1
fi

# Early Skip Flows
if command -v rustc >/dev/null 2>&1 \
    && cargo install --list 2>/dev/null | grep -q 'git-interactive-rebase-tool'; then
    pass "rust and git-interactive-rebase-tool already installed"
    exit 0
fi

if ! command -v rustc &>/dev/null; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
fi
# shellcheck source=/dev/null
source "$HOME"/.cargo/env
cargo install git-interactive-rebase-tool
