#!/bin/bash
# vim: set et fenc=utf-8 ff=unix sts=4 sw=4 ts=8 :
common_lib="$(dirname "$(readlink -f "$0")")/common-lib"
if [[ -f "$common_lib" ]]; then
    # shellcheck source=common-lib
    . "$common_lib"
else
    echo "[FAIL] Cannot find common-lib."
    exit 1
fi

# Early Skip Flows
if command -v mattermost-desktop >/dev/null 2>&1 \
    || dpkg-query -W -f='${Status}' mattermost-desktop 2>/dev/null | grep -q "install ok installed"; then
    pass "mattermost-desktop is already installed"
    exit 0
fi

curl -fsS -o- https://deb.packages.mattermost.com/setup-repo.sh | sudo env "PATH=$PATH" PDATE_GPG_KEY=yes bash
ensure_pkg mattermost-desktop
